version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./create_dbs:/docker-entrypoint-initdb.d
      - my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - '3306:3306'

volumes:
  my-db:
